# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'auth'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=${_DOCKER_HUB_USERNAME} --password=${_DOCKER_HUB_PASSWORD}']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-hugo'
    entrypoint: 'bash'
    args: ['-c', 'docker build -t yinanzhou/hugo hugo']
    waitFor: ['auth']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-wrangler'
    entrypoint: 'bash'
    args: ['-c', 'docker build -t yinanzhou/wrangler wrangler']
    waitFor: ['auth']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-firebase:database-emulator'
    entrypoint: 'bash'
    args: ['-c', 'docker build -t yinanzhou/firebase:database-emulator firebase']
    waitFor: ['auth']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker push yinanzhou/hugo']
    waitFor: ['build-hugo']
  - name: 'gcr.io/cloud-builders/wrangler'
    entrypoint: 'bash'
    args: ['-c', 'docker push yinanzhou/wrangler']
    waitFor: ['build-wrangler']
  - name: 'gcr.io/cloud-builders/firebase:database-emulator'
    entrypoint: 'bash'
    args: ['-c', 'docker push yinanzhou/firebase:database-emulator']
    waitFor: ['build-firebase:database-emulator']
options:
  logging: CLOUD_LOGGING_ONLY
